//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnn88.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vnn88.Common.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.
        /// </summary>
        public static string AnUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}.
        /// </summary>
        public static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu không thành công.
        /// </summary>
        public static string ChangePassFailed {
            get {
                return ResourceManager.GetString("ChangePassFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đúng mật khẩu!.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string ConfirmLogout {
            get {
                return ResourceManager.GetString("ConfirmLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move selected users to deffirent department?.
        /// </summary>
        public static string ConfirmMoveUser {
            get {
                return ResourceManager.GetString("ConfirmMoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid email format..
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is invalid email format..
        /// </summary>
        public static string EmailValidator {
            get {
                return ResourceManager.GetString("EmailValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is expired.
        /// </summary>
        public static string ExpiredToken {
            get {
                return ResourceManager.GetString("ExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành tìm kiếm với {0} bản ghi.
        /// </summary>
        public static string FindDataRequest {
            get {
                return ResourceManager.GetString("FindDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}.
        /// </summary>
        public static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater than or equal to {ComparisonValue}..
        /// </summary>
        public static string GreaterThanOrEqualValidator {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater than {ComparisonValue}..
        /// </summary>
        public static string GreaterThanValidator {
            get {
                return ResourceManager.GetString("GreaterThanValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password is invalid..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format..
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some invalid records. Please fix and try importing again..
        /// </summary>
        public static string InvalidImportFormat {
            get {
                return ResourceManager.GetString("InvalidImportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is invalid..
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device already registered or owned by another user or invalid..
        /// </summary>
        public static string InvalidSmartphone {
            get {
                return ResourceManager.GetString("InvalidSmartphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputed file is not a valid. This only support the extensions {0}..
        /// </summary>
        public static string InvilidExtension {
            get {
                return ResourceManager.GetString("InvilidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length can not be greater than {1} characters.
        /// </summary>
        public static string LengthNotGreaterThan {
            get {
                return ResourceManager.GetString("LengthNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length can not be less than {1} characters.
        /// </summary>
        public static string LengthNotLessThan {
            get {
                return ResourceManager.GetString("LengthNotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be between {MinLength} and {MaxLength}..
        /// </summary>
        public static string LengthValidator {
            get {
                return ResourceManager.GetString("LengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be less than or equal to {ComparisonValue}..
        /// </summary>
        public static string LessThanOrEqualValidator {
            get {
                return ResourceManager.GetString("LessThanOrEqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be less than {ComparisonValue}..
        /// </summary>
        public static string LessThanValidator {
            get {
                return ResourceManager.GetString("LessThanValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} length can not be greater than {MaxLength} characters..
        /// </summary>
        public static string MaximumLengthValidator {
            get {
                return ResourceManager.GetString("MaximumLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} length can not be less than {MinLength} characters..
        /// </summary>
        public static string MinimumLengthValidator {
            get {
                return ResourceManager.GetString("MinimumLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn đồng bộ tài khoản?.
        /// </summary>
        public static string msgSync {
            get {
                return ResourceManager.GetString("msgSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data..
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token doesn&apos;t exist..
        /// </summary>
        public static string NonExistedToken {
            get {
                return ResourceManager.GetString("NonExistedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be greater than {1}..
        /// </summary>
        public static string NotGreaterThan {
            get {
                return ResourceManager.GetString("NotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be less than {1}..
        /// </summary>
        public static string NotLessThan {
            get {
                return ResourceManager.GetString("NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} can not be blank..
        /// </summary>
        public static string NotNullValidator {
            get {
                return ResourceManager.GetString("NotNullValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a {0}..
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu!.
        /// </summary>
        public static string NullPassword {
            get {
                return ResourceManager.GetString("NullPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập lại mật khẩu!.
        /// </summary>
        public static string NullPasswordConfirm {
            get {
                return ResourceManager.GetString("NullPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a number..
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải lớn hơn hoặc bằng 6 ký tự.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token was not found..
        /// </summary>
        public static string RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token was revoked..
        /// </summary>
        public static string RefreshTokenRevoked {
            get {
                return ResourceManager.GetString("RefreshTokenRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be blank..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a file..
        /// </summary>
        public static string RequiredFile {
            get {
                return ResourceManager.GetString("RequiredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error. Please try again later..
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng.
        /// </summary>
        public static string UserLoginFailed {
            get {
                return ResourceManager.GetString("UserLoginFailed", resourceCulture);
            }
        }
    }
}
